### ISSUE TITLE
Finish the Lab for 10/30

### ISSUE THREAD

**Issue by madelynnoc** [madelynnoc/Lab04_Soil_Metals#1]
Hi, sorry this is so late, when I tried uploading my data to GitHub I had to reload Git in R which made my code disappear despite saving it! I wasn't able to get back to it til later, but this time I breezed through it. Thanks for the excellent presentation, James!

**Comment by madelynnoc** [comment]
> Hi, sorry this is so late, when I tried uploading my data to GitHub I had to reload Git in R which made my code disappear despite saving it! I wasn't able to get back to it til later, but this time I breezed through it. Thanks for the excellent presentation, James!

**Comment by vestoj** [comment]
Oh no! I wonder if you might be pushing things to GitHub differently which might have caused the issue? We can check in on this on Friday if you want! I wasn't able to find the AA tidying portion in your repository, were you able to get to it in lab?

**Comment by madelynnoc** [comment]
Yes, it is with the rest of my tidying code from that lab. Were you able to
find it?
